packages:
  perl:
    externals:
    - spec: perl@5.26.3~cpanm+opcode+open+shared+threads
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.6.0
      prefix: /usr
#  cmake:
#    externals:
#    - spec: cmake@3.26.5
#      prefix: /usr
  ninja:
    externals:
    - spec: ninja@1.8.2
      prefix: /usr
  python:
    externals:
    - spec: python@3.9.19+bz2+crypt+ctypes+dbm+lzma~nis+pyexpat+pythoncmd+readline~sqlite3+ssl+tix+tkinter+uuid+zlib
      prefix: /opt/parallelcluster/pyenv/versions/3.9.19/envs/awsbatch_virtualenv
    - spec: python@3.6.8+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
      prefix: /usr
  curl:
    externals:
    - spec: curl@7.61.1+gssapi+ldap+nghttp2
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.1+lex
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@6.5
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.3
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.1.1k
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.30
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.5
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.1
      prefix: /usr
  zlib:
    externals:
    - spec: zlib@1.2.11
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
  git:
    externals:
    - spec: git@2.43.5~tcltk
      prefix: /usr
  pkgconf:
    externals:
    - spec: pkgconf@1.4.2
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.30.123~gold~headers
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.19.8.1
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@8.0p1
      prefix: /usr
  libfabric:
    externals:
    - spec: libfabric@1.21.0 fabrics=shm,sockets,tcp,udp
      prefix: /opt/amazon/efa
  slurm:
    externals:
    - spec: slurm@23.11.7
      prefix: /opt/slurm
  openmpi:
    externals:
    - spec: openmpi@4.1.6%gcc@=8.5.0+atomics~cuda~cxx~cxx_exceptions~java~memchecker+pmi~static~wrapper-rpath
        fabrics=ofi schedulers=slurm
      prefix: /opt/amazon/openmpi
    - spec: openmpi@5.0.2%gcc@=8.5.0+atomics~cuda~cxx~cxx_exceptions~java~memchecker+pmi~static~wrapper-rpath
        fabrics=ofi schedulers=slurm
    buildable: false
  pmix:
    externals:
    - spec: pmix@4.2.8%8.5.0
      prefix: /opt/amazon/pmix
    buildable: false
