spack:
  include:
  - /modeling/spack/etc/spack/compilers.yaml
  concretizer:
    unify: true
  modules:
    default:
      enable:
      - tcl
      - lmod
  specs:
  - intel-oneapi-compilers@2022.1.0
  - intel-oneapi-mpi@2021.9.0
  - netcdf-fortran@4.6.0 ^intel-oneapi-mpi@2021.9.0+external-libfabric
  - hdf5@1.14.0 +hl +mpi ~tools ~szip +shared
  - netcdf-c@4.9.2 +mpi ~dap ~szip +shared
  - perl@5.26.3
  - parallel-netcdf@1.12.2
  - parallelio@2.5.10 +fortran~pnetcdf
  # - zlib@1.2.11
  - nco
  packages:
    all:
      providers:
        mpi: [intel-oneapi-mpi@2021.9.0]
      require:
      - any_of: ['%intel@2021.6.0', '%intel', '%gcc', '%gcc@12.2.0']
      - any_of: [build_type=Release, '@:']
      - any_of: [~shared, '@:']
      - any_of: [+pic, '@:']
      - any_of: [cmake@3.27.9%gcc@12.2.0]
    libxml2:
      require: +shared
    gettext:
      require: +shared
    netcdf-c:
      require: build_system=autotools
    netcdf-fortran:
      require: build_system=autotools
    perl:
      require: '@5.26.3'
      externals:
      - spec: perl@5.26.3~cpanm+opcode+open+shared+threads
        prefix: /usr
    cmake:
      externals:
      - spec: cmake@3.27.9%gcc@12.2.0
        prefix: /modeling/spack/opt/spack/linux-rocky8-haswell/gcc-12.2.0/cmake-3.27.9-hc7lzzkr4awwrcdxzxl5ju2iua3f6h2s
